# Starship Prompt Configuration

# Inserts a blank line between shell prompts
add_newline = true

# Configuration for the prompt format
format = """
[î‚°](bg:#464347 fg:#65737E)\
$os\
$username\
$hostname\
$directory\
$aws\
$azure\
(â†“ Source control - for right side â†“)\
$git_branch\
$git_commit\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$time\
[î‚´](fg:#464347)\
$line_break\
[î‚°](bg:#464347 fg:#65737E)\
$character
"""

# Timeout for scanning files in the directory (milliseconds)
scan_timeout = 20


# Configuration for the OS module
[os]
format = "[[î‚°](bg:#65737E fg:#464347)$symbol[î‚°](bg:#464347 fg:#65737E)]($style)"
style = "bg:#65737E fg:#EEEEEE"
disabled = false

# Custom symbols for various operating systems
# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ï†’ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ğŸ´ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "î˜ª "

# Configuration for the username module
[username]
show_always = true
style_root = "bg:#6E741C #eceff4"
style_user = "bg:#6E741C #eceff4"
format = "[[î‚°](bg:#6E741C fg:#464347)$user[î‚°](bg:#464347 fg:#6E741C)]($style)"

# Configuration for the ROOT module
# [username]
# show_always = true
# style_root = "bg:#bf616a fg:bold #eceff4"
# style_user = "bg:#bf616a fg:bold #eceff4"
# format = "[[î‚°](bg:#bf616a fg:#464347)$user[î‚°](bg:#464347 fg:#bf616a)]($style)"

# Configuration for the hostname module
[hostname]
ssh_only = false
format = "[[î‚°](bg:#9FA251 fg:#464347)[$ssh_symbol](bold) $hostname(bold red) [î‚°](bg:#464347 fg:#9FA251)]($style)"
style = "bg:#9FA251 fg:#1B2B34"
disabled = false
ssh_symbol="î¬ "

# Configuration for the directory module
[directory]
style = "bg:#98BE36 fg:#1B2B34"
read_only = " ï€£ "
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#98BE36 fg:#464347)$path$read_only[î‚°](bg:#464347 fg:#98BE36)]($style)"

# Custom substitutions for long paths
[directory.substitutions]
"~/Documents" = "ï¼ "
"~/Music" = "ï€ "
"~/Movies" = "ó° "
"~/Pictures" = "ï€¾ "
"~/Downloads" = "ï€™ "
"~/Sources" = "ï„¡"
"~/Documentos" = "ï¼ "
"~/MÃºsica" = "ï€ "
"~/VÃ­deos" = "ó° "
"~/ImÃ¡genes" = "ï€¾ "
"~/Descargas" = "ï€™ "
"/git"="GITs "
"~" = "ï€• "
#"/" = " î‚± "
# Add more substitutions as needed

# Configuration for the git branch module
[git_branch]
symbol = "ó°Š¢ "
style = "bg:#ACC172 fg:#1B2B34"
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[[î‚°](bg:#ACC172 fg:#464347)( $symbol$branch )]($style)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "


[git_status]
style = "bg:#ACC172 fg:#1B2B34"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨${count} "
behind = "ğŸ˜°${count} "
diverged = "ğŸ˜µ${count} "
up_to_date = "âœ“${count} "
untracked = "ğŸ¤·${count} "
stashed = "ğŸ“¦ ${count} "
modified = "ğŸ“${count} "
staged = "++${count} "
renamed = "ğŸ‘…${count} "
deleted = "ğŸ—‘${count} "
format = "[(î‚± $all_status$ahead_behind )[î‚°](bg:#464347 fg:#ACC172)]($style)"

# [aws]
# style = "bg:#FF9900 fg:#1B2B34"
# symbol = 'ï‰° '
# format = "[[î‚°](bg:#FF9900 fg:#464347)on [$symbol($profile )(\($region\) )]($style)[î‚°](bg:#464347 fg:#FF9900)]($style)"


# [aws.region_aliases]
# us-east-2='US-OH'
# us-east-1='US-VA'
# us-west-1='US-CA'
# us-west-2='US-OR'
# af-south-1='ZA-CT'
# ap-east-1='HK'
# ap-south-2='IN-TS'
# ap-southeast-3='ID-JK'
# ap-southeast-4='AU-VIC'
# ap-south-1='IN-MH'
# ap-northeast-3='JP-OS'
# ap-northeast-2='KR-SE'
# ap-southeast-1='SG'
# ap-southeast-2='AU-NSW'
# ap-northeast-1='JP-13'
# ca-central-1='US-CENTRAL'
# eu-central-1='DE-HE'
# eu-west-1='IE'
# eu-west-2='UK-ENG'
# eu-south-1='IT-MI'
# eu-west-3='FR-75'
# eu-south-2='ES'
# eu-north-1='SE-SE'
# eu-central-2='CH-ZH'
# il-central-1='IL'
# me-south-1='BH'
# me-central-1='AE'
# sa-east-1='BR-SP'
# us-gov-east-1='US-EASTERN'
# us-gov-west-1='US-WESTERN'

#[azure]
# style = "bg:#088DD7 fg:#ffffff"
# symbol = 'â˜ '
# format = "[[î‚°](bg:#088DD7 fg:#464347)( on [$symbol($username)] )]($style)"


# Configuration for the time module
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#789E39 #1B2B34"
format = '[[î‚°](fg:#464347 bg:#789E39)ğŸ•™$time [î‚°](bg:#464347 fg:#789E39)]($style)'


# Configuration for the character module
[character]
success_symbol = "[[î‚°](bg:#AFD700 fg:#464347)î‚°](fg:#AFD700)"
error_symbol = "[[î‚°](bg:#ff3322 fg:#464347)î‚°](fg:#ff3322)"
vicmd_symbol = "[[î‚°](bg:#6f6a70 fg:#464347)î‚³[î‚°](bg:#464347 fg:#6f6a70)](bold bg:#6f6a70 fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"
