# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#î‚¶disabled = true

format = """
[â–‘â–’â–“](bg:#2e3440 fg:#65737E)\
$os\
$username\
$hostname\
$directory\
(â†“ Source control - for right side â†“)\
$git_branch\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
(â†“ Toolchain version modules â†“)\
(â†“ on input line â†“)\
[î‚´](fg:#464347)\
$fill\
$time\
$line_break\
$character
"""

scan_timeout = 20

# Disable the blank line at the start of the prompt
# add_newline = false

[fill]
symbol="  "

# You can also replace your username with a neat symbol like ï„  to save some space
[os]
format = "[(bg:#65737E fg:#464347) $symbol[î‚°](bg:#464347 fg:#65737E)]($style)"
style = "bg:#65737E fg:#EEEEEE"
disabled = false
# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[username]
show_always = true
style_root = "bold bg:#EC5F67 fg:#EEEEEE"
style_user = "bold bg:#6699CC fg:#EEEEEE"
format = "[[î‚°](bg:#6699CC fg:#464347)$user[î‚°](bg:#464347 fg:#6699CC)]($style)"

# [sudo]
# style = "bold green bg:#9A348E"
# symbol = "ğŸ‘© "
# disabled = false
#
# # ~/.config/starship.toml

[hostname]
ssh_only = false
format = "[[î‚°](bg:#5FB3B3 fg:#464347)[$ssh_symbol](bold) $hostname(bold red) [î‚°](bg:#464347 fg:#5FB3B3)]($style)"
style= "bg:#5FB3B3 fg:#111111"
disabled = false
ssh_symbol='î¬ '

[directory]
style = "bg:#99C794 fg:#111111"
read_only = " ï ½ "
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#99C794 fg:#464347)$path$read_only[î‚°](bg:#464347 fg:#99C794)]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = "ï¼ "
"~/Music" = "ï€ "
"~/Movies" = "ï¢€ "
"~/Pictures" = "ï€¾ "
"~/Downloads" = "ï€™ "
"~/Sources" = "ï„¡"
"~/Documentos" = "ï¼ "
"~/MÃºsica" = "ï€ "
"~/VÃ­deos" = "ï¢€ "
"~/ImÃ¡genes" = "ï€¾ "
"~/Descargas" = "ï€™ "
"/git"="GITs "
"~" = "ï€• "
#"/" = " î‚± "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

# [cmd_duration]
# # disabled = true
# style = "bg:#625d63 fg:#FBDE2D"
# min_time = 2_000
# show_milliseconds = true
# show_notifications = false
# min_time_to_notify = 45_000
# format = "[[î‚°](bg:#625d63 fg:#464347) â±ï¸ $duration[î‚°](bg:#464347 fg:#625d63)]($style)"

[git_branch]
symbol = "ï¡ "
style = "bg:#FAC863 fg:#111111"
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[[î‚°](bg:#FAC863 fg:#464347)( $symbol$branch )[î‚°](bg:#464347 fg:#FAC863)]($style)"

# [aws]
# style = "bg:#FF9900 fg:#1B2B34"
# symbol = 'ï‰° '
#format = "[[î‚°](bg:#FF9900 fg:#464347)( $symbol$branch )[î‚°](bg:#464347 fg:#FF9900)]($style)"


# [aws.region_aliases]
# us-east-2='US-OH'
# us-east-1='US-VA'
# us-west-1='US-CA'
# us-west-2='US-OR'
# af-south-1='ZA-CT'
# ap-east-1='HK'
# ap-south-2='IN-TS'
# ap-southeast-3='ID-JK'
# ap-southeast-4='AU-VIC'
# ap-south-1='IN-MH'
# ap-northeast-3='JP-OS'
# ap-northeast-2='KR-SE'
# ap-southeast-1='SG'
# ap-southeast-2='AU-NSW'
# ap-northeast-1='JP-13'
# ca-central-1='US-CENTRAL'
# eu-central-1='DE-HE'
# eu-west-1='IE'
# eu-west-2='UK-ENG'
# eu-south-1='IT-MI'
# eu-west-3='FR-75'
# eu-south-2='ES'
# eu-north-1='SE-SE'
# eu-central-2='CH-ZH'
# il-central-1='IL'
# me-south-1='BH'
# me-central-1='AE'
# sa-east-1='BR-SP'
# us-gov-east-1='US-EASTERN'
# us-gov-west-1='US-WESTERN'

#[azure]
# style = "bg:#088DD7 fg:#ffffff"
# symbol = 'â˜ '
#format = "[[î‚°](bg:#FF9900 fg:#464347)( $symbol$branch )[î‚°](bg:#464347 fg:#FF9900)]($style)"

[line_break]
disabled = false

[docker_context]
symbol = " ğŸ³ "
style = "bg:#65737E fg:#464347"
format = "[[î‚°](bg:#65737E fg:#464347)$symbol$context[î‚°](bg:#464347 fg:#65737E)]($style)"


[status]
# disabled = false
symbol = "ï„ª"
style = "bg:#464347 fg:#ff3322"
format = "[$symbol$status]($style)"

##########TIME MODULE###########
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8fbcbb fg:#1B2B34"
format = '[[î‚¶](fg:#464347 bg:none)[î‚²](fg:#8fbcbb bg:#464347)ğŸ•™$time [â–“â–’â–‘](bg:#464347 fg:#8fbcbb)]($style)'


###################################

[character]
success_symbol = "[[î‚°](bg:#AFD700 fg:#464347)î‚°](fg:#AFD700)"
error_symbol = "[[î‚°](bg:#ff3322 fg:#464347)î‚°](fg:#ff3322)"
vicmd_symbol = "[[î‚°](bg:#6f6a70 fg:#464347)î‚³[î‚°](bg:#464347 fg:#6f6a70)](bold bg:#6f6a70 fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"

