# Starship Prompt Configuration

# Inserts a blank line between shell prompts
add_newline = true

# Custom symbols for different operating systems
[os.symbols]
Windows = "ï…º "
Linux = "ï…¼ "
macOS = "ï…¹ "
# Add symbols for other operating systems as needed

# Configuration for the prompt format
format = """
[î‚°](bg:#464347 fg:#8FBCBB)\
$os\
$username\
$hostname\
$directory\
(â†“ Source control - for right side â†“)\
$git_branch\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$time\
[î‚´](fg:#464347)\
$line_break\
[î‚°](bg:#464347 fg:#8FBCBB)\
$character
"""

# Timeout for scanning files in the directory (milliseconds)
scan_timeout = 20

# Configuration for the OS module
[os]
format = "[[î‚°](bg:#65737E fg:#464347)$symbol[î‚°](bg:#464347 fg:#65737E)]($style)"
style = "bg:#65737E fg:#EEEEEE"
disabled = false

# Custom symbols for various operating systems
# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

# Configuration for the username module
[username]
show_always = true
style_root = "bold bg:#EC5F67 fg:#EEEEEE"
style_user = "bold bg:#5E81AC fg:#EEEEEE"
format = "[[î‚°](bg:#5E81AC fg:#464347)$user[î‚°](bg:#464347 fg:#5E81AC)]($style)"

# Configuration for the hostname module
[hostname]
ssh_only = false
format = "[[î‚°](bg:#81A1C1 fg:#464347)[$ssh_symbol](bold) $hostname(bold red) [î‚°](bg:#464347 fg:#81A1C1)]($style)"
style = "bg:#81A1C1 fg:#111111"
disabled = false
ssh_symbol='î¬ '

# Configuration for the directory module
[directory]
style = "bg:#88C0D0 fg:#111111"
read_only = " ï ½ "
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#88C0D0 fg:#464347)$path$read_only[î‚°](bg:#464347 fg:#88C0D0)]($style)"

# Custom substitutions for long paths
[directory.substitutions]
"~/Documents" = "ï¼ "
"~/Music" = "ï€ "
"~/Movies" = "ï¢€ "
"~/Pictures" = "ï€¾ "
"~/Downloads" = "ï€™ "
"~/Sources" = "ï„¡"
"~/Documentos" = "ï¼ "
"~/MÃºsica" = "ï€ "
"~/VÃ­deos" = "ï¢€ "
"~/ImÃ¡genes" = "ï€¾ "
"~/Descargas" = "ï€™ "
"/git"="GITs "
"~" = "ï€• "
#"/" = " î‚± "
# Add more substitutions as needed

# Configuration for the git branch module
[git_branch]
symbol = "ï¡ "
style = "bg:#EBCB8B fg:#111111"
truncation_length = 6
truncation_symbol = ""
format = "[[î‚°](bg:#EBCB8B fg:#464347)( $symbol$branch )]($style)"

# Configuration for the git status module
[git_status]
style = "bg:#EBCB8B fg:#111111"
# Add any additional git status configurations as needed

# Configuration for the time module
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C594C5 fg:#1B2B34"
format = '[[î‚°](fg:#464347 bg:#C594C5) ğŸ•™ $time [î‚°](bg:#464347 fg:#C594C5)]($style)'

# Configuration for a custom weather module
[custom.weather]
when = true
time_format = "%R" # Hour:Minute Format
style = "bg:#C594C5 fg:#1B2B34"
command = "curl -s 'wttr.in/Barcelona?format=%c%t'"
format = '[ $output [î‚°](bg:#464347 fg:#C594C5)]($style)'

# Configuration for the character module
[character]
success_symbol = "[[î‚°](bg:#AFD700 fg:#464347)î‚°](fg:#AFD700)"
error_symbol = "[[î‚°](bg:#ff3322 fg:#464347)î‚°](fg:#ff3322)"
vicmd_symbol = "[[î‚°](bg:#6f6a70 fg:#464347)î‚³[î‚°](bg:#464347 fg:#6f6a70)](bold bg:#6f6a70 fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"