# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#î‚¶disabled = true

format = """
[î‚°](bg:#3E4247 fg:#E5E9F0)\
$os\
$username\
$hostname\
$directory\
(â†“ Source control - for right side â†“)\
$git_branch\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$docker_context\
$php\
$python\
$rust\
$c\
(â†“ Toolchain version modules â†“)\
(â†“ on input line â†“)\
$time\
[î‚´](fg:#E5E9F0)\
$line_break\
[î‚°](bg:#E5E9F0 fg:#3E4247)\
$character
"""

scan_timeout = 20

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[os]
format = "[[î‚°](bg:#5FB3B3 fg:#E5E9F0)$symbol[î‚°](bg:#E5E9F0 fg:#5FB3B3)]($style)"
style= "bg:#5FB3B3 fg:#EEEEEE"
disabled = false

# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[username]
show_always = true
style_root = "bold bg:#E5E9F0 fg:#EEEEEE"
style_user = "bold bg:#8B949E fg:#EEEEEE"
format = "[[î‚°](bg:#8B949E fg:#E5E9F0)$user[î‚°](bg:#E5E9F0 fg:#8B949E)]($style)"

# [sudo]
# style = "bold green bg:#9A348E"
# symbol = "ğŸ‘© "
# disabled = false
#
# # ~/.config/starship.toml

[hostname]
ssh_only = false
format = "[[î‚°](bg:#B4BEC5 fg:#E5E9F0)[$ssh_symbol](bold) $hostname(bold red) [î‚°](bg:#E5E9F0 fg:#B4BEC5)]($style)"
style= "bg:#B4BEC5 fg:#111111"
disabled = false
ssh_symbol='î¬ '

