# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#î‚¶disabled = true

format = """
[î‚°](bg:#464347 fg:#8FBCBB)\
$os\
$username\
$hostname\
$directory\
(â†“ Source control - for right side â†“)\
$git_branch\
$git_status\
(â†‘ Source control - for right side â†‘)\
(â†“ Toolchain version modules â†“)\
$docker_context\
$php\
$python\
$rust\
$c\
(â†“ Toolchain version modules â†“)\
(â†“ on input line â†“)\
$time\
[î‚´](fg:#464347)\
$line_break\
[î‚°](bg:#464347 fg:#8FBCBB)\
$character
"""

scan_timeout = 20

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[os]
format = "[[î‚°](bg:#65737E fg:#464347)$symbol[î‚°](bg:#464347 fg:#65737E)]($style)"
style= "bg:#65737E fg:#EEEEEE"
disabled = false

# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[username]
show_always = true
style_root = "bold bg:#EC5F67 fg:#EEEEEE"
style_user = "bold bg:#5E81AC fg:#EEEEEE"
format = "[[î‚°](bg:#5E81AC fg:#464347)$user[î‚°](bg:#464347 fg:#5E81AC)]($style)"

# [sudo]
# style = "bold green bg:#9A348E"
# symbol = "ğŸ‘© "
# disabled = false
#
# # ~/.config/starship.toml

[hostname]
ssh_only = false
format = "[[î‚°](bg:#81A1C1 fg:#464347)[$ssh_symbol](bold) $hostname(bold red) [î‚°](bg:#464347 fg:#81A1C1)]($style)"
style= "bg:#81A1C1 fg:#111111"
disabled = false
ssh_symbol='î¬ '

[directory]
style = "bg:#88C0D0 fg:#111111"
read_only = " ï ½ "
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[[î‚°](bg:#88C0D0 fg:#464347)$path$read_only[î‚°](bg:#464347 fg:#88C0D0)]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = "ï¼ "
"~/Music" = "ï€ "
"~/Movies" = "ï¢€ "
"~/Pictures" = "ï€¾ "
"~/Downloads" = "ï€™ "
"~/Sources" = "ï„¡"
"~/Documentos" = "ï¼ "
"~/MÃºsica" = "ï€ "
"~/VÃ­deos" = "ï¢€ "
"~/ImÃ¡genes" = "ï€¾ "
"~/Descargas" = "ï€™ "
"/git"="GITs "
"~" = "ï€• "
#"/" = " î‚± "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

# [cmd_duration]
# # disabled = true
# style = "bg:#8FBCBB fg:#FBDE2D"
# min_time = 2_000
# show_milliseconds = true
# show_notifications = false
# min_time_to_notify = 45_000
# format = "[[î‚°](bg:#8FBCBB fg:#464347) â±ï¸ $duration[î‚°](bg:#464347 fg:#8FBCBB)]($style)"

[git_branch]
symbol = "ï¡ "
style = "bg:#EBCB8B fg:#111111"
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[[î‚°](bg:#EBCB8B fg:#464347)( $symbol$branch )]($style)"

[git_status]
style = "bg:#EBCB8B fg:#111111"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨ ${count}"
behind = "ğŸ˜° ${count}"
diverged = "ğŸ˜µ ${count}"
up_to_date = "âœ“ ${count}"
untracked = "ğŸ¤· ${count}"
stashed = "ğŸ“¦ ${count}"
modified = "ğŸ“ ${count}"
staged = "++ ${count}"
renamed = "ğŸ‘… ${count}"
deleted = "ğŸ—‘ ${count}"
format = "[( $all_status$ahead_behind )[î‚°](bg:#464347 fg:#EBCB8B)]($style)"



# [jobs]
# # disabled = true
# symbol = " ï€º "
# style = "bold bg:#8FBCBB fg:#FFA200"
# # threshold = 1
# format = "[$symbol$number]($style)"


[line_break]
disabled = false

[docker_context]
symbol = " ğŸ³ "
style = "bg:#65737E fg:#464347"
format = "[[î‚°](bg:#65737E fg:#464347)$symbol$context[î‚°](bg:#464347 fg:#65737E)]($style)"

[python]
# disabled = true
symbol = " îˆµ "
style = "bg:#65737E fg:#111111"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[î‚°](fg:#464347 bg:#65737E)$symbol$pyenv_prefix$version(\($virtualenv\))[î‚°](bg:#464347 fg:#65737E)]($style)'

[php]
symbol = " ğŸ˜ "
style = "bg:#65737E fg:#111111"
format = "[[î‚°](bg:#65737E fg:#464347)$symbol$version[î‚°](bg:#464347 fg:#65737E)]($style)"

[rust]
symbol = " ğŸ¦€ "
style = "bg:#65737E fg:#111111"
format = "[[î‚°](bg:#65737E fg:#464347)$symbol$version[î‚°](bg:#464347 fg:#65737E)]($style)"

[c]
symbol = " î˜ "
style = "bg:#65737E fg:#111111"
format = "[[î‚°](bg:#65737E fg:#464347)$symbol$name $version[î‚°](bg:#464347 fg:#65737E)]($style)"


[status]
# disabled = false
symbol = "ï„ª"
style = "bg:#464347 fg:#ff3322"
format = "[$symbol$status]($style)"

##########TIME MODULE###########

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#F99157 fg:#111111"
# format = '[[î‚°](fg:#464347 bg:#F99157) ğŸ•™ $time  [î‚°](bg:#464347 fg:#F99157)]($style)'

###################################

##########TIME & WEATHER MODULE###########

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C594C5 fg:#1B2B34"
format = '[[î‚°](fg:#464347 bg:#C594C5) ğŸ•™ $time [î‚°](bg:#464347 fg:#C594C5)]($style)'


[custom.weather]
when=true
time_format = "%R" # Hour:Minute Format
style = "bg:#C594C5 fg:#1B2B34"
command="curl -s 'wttr.in/Barcelona?format=%c%t'"
format = '[ $output [î‚°](bg:#464347 fg:#C594C5)]($style)'

###################################

[character]
success_symbol = "[[î‚°](bg:#AFD700 fg:#464347)î‚°](fg:#AFD700)"
error_symbol = "[[î‚°](bg:#ff3322 fg:#464347)î‚°](fg:#ff3322)"
vicmd_symbol = "[[î‚°](bg:#6f6a70 fg:#464347)î‚³[î‚°](bg:#464347 fg:#6f6a70)](bold bg:#6f6a70 fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"
