# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 1000
command_timeout= 500

# Replace the "â¯" symbol in the prompt with "âœ"
#[character] # The name of the module we are configuring is "character"
#:was = "[âœ](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
#[package]
#î‚¶disabled = true

format = """
[â•­â”€](bold bg:none fg:bright-green)[â–‘â–’â–“](bg_os)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_metrics\
$git_status\
[î‚´](fg:bg_time)\
$fill\
$time\
${custom.end}\
$line_break\
$character
"""

## OCEANIC NEXT COLOR SCHEME ##
# dark1  = #1B2B34
# dark2  = #343D46
# dark3  = #4F5B66
# dark4  = #65737E
# light1  = #A7ADBA
# light2  = #C0C5CE
# light3  = #CDD3DE
# light4  = #D8DEE9
# red  = #EC5f67
# orange  = #F99157
# yellow  = #FAC863
# lime  = #CCC880
# green  = #99C794
# aqua  = #5FB3B3
# blue1  = #6699CC
# blue2 = #527296
# purple  = #C594C5
# brown  = #AB7967

palette = 'myPrompt'

[palettes.myPrompt]
bg_os = '#4F5B66'
fg_os = '#D8DEE9'
bg_user = '#4F5B66'
fg_user = '#6699CC'
bg_host = '#4F5B66'
fg_host =  '#5FB3B3'
bg_direct = '#4F5B66'
fg_direct = '#99C794'
bg_context = '#4F5B66'
fg_context = '#CCC880'
bg_git = '#4F5B66'
fg_git = '#F99157'
bg_dev = '#4F5B66'
fg_dev = '#C594C5'
bg_time= '#4F5B66'
fg_time= '#D8DEE9'


# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[[â•°â”€â¯](bold bg:none fg:bright-green)](fg:#AFD700)"
error_symbol = "[[â•°â”€](bold bg:none fg:bright-green)â¯(bright-red)](fg:#ff3322)"
vicmd_symbol = "[[â•°â”€](bold bg:none fg:bright-green)â¯(bright-blue)](fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"

### MOVE MODULES TO THE RIGHT ###
[fill]
symbol = 'â”€'
style = 'bold bright-green'

### OS NAME ###
# You can also replace your username with a neat symbol like ï„  to save some space
[os]
format = "[ $symbol]($style)[ î‚±](bold bg:bg_os fg:bright-green)"
style= "bold bg:bg_os fg:fg_os"
disabled = false

# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

### USERNAME ###
[username]
show_always = true
style_root = "bold bg:bg_user fg:bright-red"
style_user = "bold bg:bg_user fg:fg_user"
format = "[ $user]($style)"

# [sudo]
# style = "bold green bg:#9A348E"
# symbol = "ğŸ‘© "
# disabled = false
#
# # ~/.config/starship.toml


### HOSTNAME ###
[hostname]
ssh_only = false
format = "[ î‚±](bold bg:bg_os fg:bright-green)[[$ssh_symbol](bold) $hostname(bold red)]($style)"
style= "bold bg:bg_host fg:fg_host"
disabled = false
ssh_symbol='î¬ '

################## DIRECTORY MODULES ###############################

[directory]
style = "bold bg:bg_direct fg:fg_direct"
read_only = " ï ½ "
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[ î‚±](bold bg:bg_os fg:bright-green)[ $path$read_only]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = "ï¼ "
"~/Music" = "ï€ "
"~/Movies" = "ï¢€ "
"~/Pictures" = "ï€¾ "
"~/Downloads" = "ï€™ "
"~/Sources" = "ï„¡"
"~/Documentos" = "ï¼ "
"~/MÃºsica" = "ï€ "
"~/VÃ­deos" = "ï¢€ "
"~/ImÃ¡genes" = "ï€¾ "
"~/Descargas" = "ï€™ "
"/git"="GITs "
"~" = "ï€• "
#"/" = " î‚± "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

# [cmd_duration]
# # disabled = true
# style = "bg:#625d63 fg:#FBDE2D"
# min_time = 2_000
# show_milliseconds = true
# show_notifications = false
# min_time_to_notify = 45_000
# format = "[[î‚°](bg:#625d63 fg:#464347) â±ï¸ $duration[î‚°](bg:#464347 fg:#625d63)]($style)"


##################### GIT CONTEXTS ########################

[git_branch]
symbol = "ï¡ "
style = "bold bg:bg_git fg:fg_git"
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[ î‚±](bold bg:bg_os fg:bright-green)[( $symbol$branch )]($style)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_metrics]
added_style = "bold bg:bg_git fg:fg_git"
format = "[$added]($added_style)/[-$deleted]($deleted_style)"
# format = "[$added]($added_style)/[-$deleted]($deleted_style)"

[git_status]
style = "bg:bg_git fg:fg_git"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨${count }"
behind = "ğŸ˜°${count} "
diverged = "ğŸ˜µ${count} "
up_to_date = "âœ“${count} "
untracked = "ğŸ¤·${count} "
stashed = "ğŸ“¦${count} "
modified = "ğŸ“${count} "
staged = "++${count} "
renamed = "ğŸ‘…${count} "
deleted = "ğŸ—‘${count} "
format = "[($all_status$ahead_behind)]($style)"

# [jobs]
# # disabled = true
# symbol = " ï€º "
# style = "bold bg:#625d63 fg:#FFA200"
# # threshold = 1
# format = "[$symbol$number]($style)"

##################### DOCKER CONTEXTS ########################

[docker_context]
symbol = " ğŸ³ "
style = "bg:bg_context fg:fg_context"
format = "[ î‚±](bold bg:bg_os fg:bright-green)[$symbol$context]($style)"

############## DEVELOPMENT LANGUAGE MODULES #################

[python]
# disabled = true
symbol = " îˆµ "
style = "bg:bg_dev fg:fg_dev"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[ î‚±](bold bg:bg_os fg:bright-green)[$symbol$pyenv_prefix$version(\($virtualenv\))]($style)'

[php]
symbol = " ğŸ˜ "
style = "bg:bg_dev fg:fg_dev"
format = "[ î‚±](bold bg:bg_os fg:bright-green)[$symbol$version]($style)"

[rust]
symbol = " ğŸ¦€ "
style = "bg:bg_dev fg:fg_dev"
format = "[ î‚±](bold bg:bg_os fg:bright-green)[$symbol$version]($style)"

[c]
symbol = " î˜ "
style = "bg:bg_dev fg:fg_dev"
format = "[ î‚±](bold bg:bg_os fg:bright-green)[$symbol$name $version]($style)"

###################### TIME MODULE ##########################

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:orange fg:#111111"
# format = '[[î‚°](fg:#464347 bg:orange) ğŸ•™ $time  [î‚°](bg:#464347 fg:orange)]($style)'


################### TIME & WEATHER MODULE ###################

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bg_time fg:fg_time"
format = '[[î‚¶](fg:bg_time bg:none) ğŸ•™ $time]($style)'

[custom.end]
when=true
style = "bold bg:bg_time fg:fg_time"
format = '[ $output [â–“â–’â–‘](bg_time)]($style)'
#[â”€â•¯](bold bg:none fg:bright-green)

